"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.IsolatedAsyncioTestCase):
    """TransactionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TransactionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_transaction(self) -> None:
        """Test case for create_transaction

        Create a single transaction or multiple transactions
        """
        pass

    async def test_delete_transaction(self) -> None:
        """Test case for delete_transaction

        Delete a transaction
        """
        pass

    async def test_get_transaction_by_id(self) -> None:
        """Test case for get_transaction_by_id

        Get a transaction
        """
        pass

    async def test_get_transactions(self) -> None:
        """Test case for get_transactions

        Get all transactions
        """
        pass

    async def test_get_transactions_by_account(self) -> None:
        """Test case for get_transactions_by_account

        Get all account transactions
        """
        pass

    async def test_get_transactions_by_category(self) -> None:
        """Test case for get_transactions_by_category

        Get all category transactions
        """
        pass

    async def test_get_transactions_by_month(self) -> None:
        """Test case for get_transactions_by_month

        Get all plan month transactions
        """
        pass

    async def test_get_transactions_by_payee(self) -> None:
        """Test case for get_transactions_by_payee

        Get all payee transactions
        """
        pass

    async def test_import_transactions(self) -> None:
        """Test case for import_transactions

        Import transactions
        """
        pass

    async def test_update_transaction(self) -> None:
        """Test case for update_transaction

        Update a transaction
        """
        pass

    async def test_update_transactions(self) -> None:
        """Test case for update_transactions

        Update multiple transactions
        """
        pass


if __name__ == "__main__":
    unittest.main()
