"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.models.plan_detail import PlanDetail


class TestPlanDetail(unittest.TestCase):
    """PlanDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanDetail:
        """Test PlanDetail
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlanDetail`
        """
        model = PlanDetail()
        if include_optional:
            return PlanDetail(
                id = '',
                name = '',
                last_modified_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                first_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                last_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_format = asyncio_for_ynab.models.date_format.DateFormat(
                    format = '', ),
                currency_format = asyncio_for_ynab.models.currency_format.CurrencyFormat(
                    iso_code = '',
                    example_format = '',
                    decimal_digits = 56,
                    decimal_separator = '',
                    symbol_first = True,
                    group_separator = '',
                    currency_symbol = '',
                    display_symbol = True, ),
                accounts = [
                    asyncio_for_ynab.models.account_base.AccountBase(
                        id = '',
                        name = '',
                        type = 'checking',
                        on_budget = True,
                        closed = True,
                        note = '',
                        balance = 56,
                        cleared_balance = 56,
                        uncleared_balance = 56,
                        transfer_payee_id = '',
                        direct_import_linked = True,
                        direct_import_in_error = True,
                        last_reconciled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        debt_original_balance = 56,
                        debt_interest_rates = {
                            'key' : 56
                            },
                        debt_minimum_payments = {
                            'key' : 56
                            },
                        debt_escrow_amounts = ,
                        deleted = True, )
                    ],
                payees = [
                    asyncio_for_ynab.models.payee.Payee(
                        id = '',
                        name = '',
                        transfer_account_id = '',
                        deleted = True, )
                    ],
                payee_locations = [
                    asyncio_for_ynab.models.payee_location.PayeeLocation(
                        id = '',
                        payee_id = '',
                        latitude = '',
                        longitude = '',
                        deleted = True, )
                    ],
                category_groups = [
                    asyncio_for_ynab.models.category_group.CategoryGroup(
                        id = '',
                        name = '',
                        hidden = True,
                        deleted = True, )
                    ],
                categories = [
                    asyncio_for_ynab.models.category_base.CategoryBase(
                        id = '',
                        category_group_id = '',
                        category_group_name = '',
                        name = '',
                        hidden = True,
                        original_category_group_id = '',
                        note = '',
                        budgeted = 56,
                        activity = 56,
                        balance = 56,
                        goal_type = 'TB',
                        goal_needs_whole_amount = True,
                        goal_day = 56,
                        goal_cadence = 56,
                        goal_cadence_frequency = 56,
                        goal_creation_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        goal_target = 56,
                        goal_target_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        goal_target_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        goal_percentage_complete = 56,
                        goal_months_to_budget = 56,
                        goal_under_funded = 56,
                        goal_overall_funded = 56,
                        goal_overall_left = 56,
                        goal_snoozed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        deleted = True, )
                    ],
                months = [
                    null
                    ],
                transactions = [
                    asyncio_for_ynab.models.transaction_summary_base.TransactionSummaryBase(
                        id = '',
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        amount = 56,
                        memo = '',
                        cleared = 'cleared',
                        approved = True,
                        flag_color = 'red',
                        flag_name = '',
                        account_id = '',
                        payee_id = '',
                        category_id = '',
                        transfer_account_id = '',
                        transfer_transaction_id = '',
                        matched_transaction_id = '',
                        import_id = '',
                        import_payee_name = '',
                        import_payee_name_original = '',
                        debt_transaction_type = 'payment',
                        deleted = True, )
                    ],
                subtransactions = [
                    asyncio_for_ynab.models.sub_transaction_base.SubTransactionBase(
                        id = '',
                        transaction_id = '',
                        amount = 56,
                        memo = '',
                        payee_id = '',
                        payee_name = '',
                        category_id = '',
                        category_name = '',
                        transfer_account_id = '',
                        transfer_transaction_id = '',
                        deleted = True, )
                    ],
                scheduled_transactions = [
                    asyncio_for_ynab.models.scheduled_transaction_summary_base.ScheduledTransactionSummaryBase(
                        id = '',
                        date_first = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        date_next = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                        frequency = 'never',
                        amount = 56,
                        memo = '',
                        flag_color = 'red',
                        flag_name = '',
                        account_id = '',
                        payee_id = '',
                        category_id = '',
                        transfer_account_id = '',
                        deleted = True, )
                    ],
                scheduled_subtransactions = [
                    asyncio_for_ynab.models.scheduled_sub_transaction_base.ScheduledSubTransactionBase(
                        id = '',
                        scheduled_transaction_id = '',
                        amount = 56,
                        memo = '',
                        payee_id = '',
                        payee_name = '',
                        category_id = '',
                        category_name = '',
                        transfer_account_id = '',
                        deleted = True, )
                    ]
            )
        else:
            return PlanDetail(
                id = '',
                name = '',
        )
        """

    def testPlanDetail(self):
        """Test PlanDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
