"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.api.categories_api import CategoriesApi


class TestCategoriesApi(unittest.IsolatedAsyncioTestCase):
    """CategoriesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CategoriesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_category(self) -> None:
        """Test case for create_category

        Create a category
        """
        pass

    async def test_create_category_group(self) -> None:
        """Test case for create_category_group

        Create a category group
        """
        pass

    async def test_get_categories(self) -> None:
        """Test case for get_categories

        Get all categories
        """
        pass

    async def test_get_category_by_id(self) -> None:
        """Test case for get_category_by_id

        Get a category
        """
        pass

    async def test_get_month_category_by_id(self) -> None:
        """Test case for get_month_category_by_id

        Get a category for a specific plan month
        """
        pass

    async def test_update_category(self) -> None:
        """Test case for update_category

        Update a category
        """
        pass

    async def test_update_category_group(self) -> None:
        """Test case for update_category_group

        Update a category group
        """
        pass

    async def test_update_month_category(self) -> None:
        """Test case for update_month_category

        Update a category for a specific month
        """
        pass


if __name__ == "__main__":
    unittest.main()
