"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.models.month_detail import MonthDetail


class TestMonthDetail(unittest.TestCase):
    """MonthDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonthDetail:
        """Test MonthDetail
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MonthDetail`
        """
        model = MonthDetail()
        if include_optional:
            return MonthDetail(
                month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                note = '',
                income = 56,
                budgeted = 56,
                activity = 56,
                to_be_budgeted = 56,
                age_of_money = 56,
                deleted = True,
                income_formatted = '',
                income_currency = 1.337,
                budgeted_formatted = '',
                budgeted_currency = 1.337,
                activity_formatted = '',
                activity_currency = 1.337,
                to_be_budgeted_formatted = '',
                to_be_budgeted_currency = 1.337,
                categories = [
                    null
                    ]
            )
        else:
            return MonthDetail(
                month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                income = 56,
                budgeted = 56,
                activity = 56,
                to_be_budgeted = 56,
                deleted = True,
                categories = [
                    null
                    ],
        )
        """

    def testMonthDetail(self):
        """Test MonthDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
