"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.api.user_api import UserApi


class TestUserApi(unittest.IsolatedAsyncioTestCase):
    """UserApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UserApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_user(self) -> None:
        """Test case for get_user

        Get user
        """
        pass


if __name__ == "__main__":
    unittest.main()
