"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.models.plan_summary_response import PlanSummaryResponse


class TestPlanSummaryResponse(unittest.TestCase):
    """PlanSummaryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanSummaryResponse:
        """Test PlanSummaryResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlanSummaryResponse`
        """
        model = PlanSummaryResponse()
        if include_optional:
            return PlanSummaryResponse(
                data = asyncio_for_ynab.models.plan_summary_response_data.PlanSummaryResponse_data(
                    plans = [
                        asyncio_for_ynab.models.plan_summary.PlanSummary(
                            id = '',
                            name = '',
                            last_modified_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                            first_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                            last_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                            date_format = asyncio_for_ynab.models.date_format.DateFormat(
                                format = '', ),
                            currency_format = asyncio_for_ynab.models.currency_format.CurrencyFormat(
                                iso_code = '',
                                example_format = '',
                                decimal_digits = 56,
                                decimal_separator = '',
                                symbol_first = True,
                                group_separator = '',
                                currency_symbol = '',
                                display_symbol = True, ),
                            accounts = [
                                null
                                ], )
                        ],
                    default_plan = null, )
            )
        else:
            return PlanSummaryResponse(
                data = asyncio_for_ynab.models.plan_summary_response_data.PlanSummaryResponse_data(
                    plans = [
                        asyncio_for_ynab.models.plan_summary.PlanSummary(
                            id = '',
                            name = '',
                            last_modified_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                            first_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                            last_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                            date_format = asyncio_for_ynab.models.date_format.DateFormat(
                                format = '', ),
                            currency_format = asyncio_for_ynab.models.currency_format.CurrencyFormat(
                                iso_code = '',
                                example_format = '',
                                decimal_digits = 56,
                                decimal_separator = '',
                                symbol_first = True,
                                group_separator = '',
                                currency_symbol = '',
                                display_symbol = True, ),
                            accounts = [
                                null
                                ], )
                        ],
                    default_plan = null, ),
        )
        """

    def testPlanSummaryResponse(self):
        """Test PlanSummaryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
