"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.IsolatedAsyncioTestCase):
    """AccountsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AccountsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_account(self) -> None:
        """Test case for create_account

        Create an account
        """
        pass

    async def test_get_account_by_id(self) -> None:
        """Test case for get_account_by_id

        Get an account
        """
        pass

    async def test_get_accounts(self) -> None:
        """Test case for get_accounts

        Get all accounts
        """
        pass


if __name__ == "__main__":
    unittest.main()
