"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.api.plans_api import PlansApi


class TestPlansApi(unittest.IsolatedAsyncioTestCase):
    """PlansApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PlansApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_plan_by_id(self) -> None:
        """Test case for get_plan_by_id

        Get a plan
        """
        pass

    async def test_get_plan_settings_by_id(self) -> None:
        """Test case for get_plan_settings_by_id

        Get plan settings
        """
        pass

    async def test_get_plans(self) -> None:
        """Test case for get_plans

        Get all plans
        """
        pass


if __name__ == "__main__":
    unittest.main()
