"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.models.month_summaries_response import MonthSummariesResponse


class TestMonthSummariesResponse(unittest.TestCase):
    """MonthSummariesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonthSummariesResponse:
        """Test MonthSummariesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MonthSummariesResponse`
        """
        model = MonthSummariesResponse()
        if include_optional:
            return MonthSummariesResponse(
                data = asyncio_for_ynab.models.month_summaries_response_data.MonthSummariesResponse_data(
                    months = [
                        null
                        ],
                    server_knowledge = 56, )
            )
        else:
            return MonthSummariesResponse(
                data = asyncio_for_ynab.models.month_summaries_response_data.MonthSummariesResponse_data(
                    months = [
                        null
                        ],
                    server_knowledge = 56, ),
        )
        """

    def testMonthSummariesResponse(self):
        """Test MonthSummariesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
