"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.api.scheduled_transactions_api import ScheduledTransactionsApi


class TestScheduledTransactionsApi(unittest.IsolatedAsyncioTestCase):
    """ScheduledTransactionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ScheduledTransactionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_scheduled_transaction(self) -> None:
        """Test case for create_scheduled_transaction

        Create a scheduled transaction
        """
        pass

    async def test_delete_scheduled_transaction(self) -> None:
        """Test case for delete_scheduled_transaction

        Delete a scheduled transaction
        """
        pass

    async def test_get_scheduled_transaction_by_id(self) -> None:
        """Test case for get_scheduled_transaction_by_id

        Get a scheduled transaction
        """
        pass

    async def test_get_scheduled_transactions(self) -> None:
        """Test case for get_scheduled_transactions

        Get all scheduled transactions
        """
        pass

    async def test_update_scheduled_transaction(self) -> None:
        """Test case for update_scheduled_transaction

        Update a scheduled transaction
        """
        pass


if __name__ == "__main__":
    unittest.main()
