"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.api.payees_api import PayeesApi


class TestPayeesApi(unittest.IsolatedAsyncioTestCase):
    """PayeesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PayeesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_payee(self) -> None:
        """Test case for create_payee

        Create a payee
        """
        pass

    async def test_get_payee_by_id(self) -> None:
        """Test case for get_payee_by_id

        Get a payee
        """
        pass

    async def test_get_payees(self) -> None:
        """Test case for get_payees

        Get all payees
        """
        pass

    async def test_update_payee(self) -> None:
        """Test case for update_payee

        Update a payee
        """
        pass


if __name__ == "__main__":
    unittest.main()
