"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.83.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from asyncio_for_ynab.models.payee_location_response import PayeeLocationResponse


class TestPayeeLocationResponse(unittest.TestCase):
    """PayeeLocationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayeeLocationResponse:
        """Test PayeeLocationResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PayeeLocationResponse`
        """
        model = PayeeLocationResponse()
        if include_optional:
            return PayeeLocationResponse(
                data = asyncio_for_ynab.models.payee_location_response_data.PayeeLocationResponse_data(
                    payee_location = asyncio_for_ynab.models.payee_location.PayeeLocation(
                        id = '',
                        payee_id = '',
                        latitude = '',
                        longitude = '',
                        deleted = True, ), )
            )
        else:
            return PayeeLocationResponse(
                data = asyncio_for_ynab.models.payee_location_response_data.PayeeLocationResponse_data(
                    payee_location = asyncio_for_ynab.models.payee_location.PayeeLocation(
                        id = '',
                        payee_id = '',
                        latitude = '',
                        longitude = '',
                        deleted = True, ), ),
        )
        """

    def testPayeeLocationResponse(self):
        """Test PayeeLocationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
