# these are generated
exclude: |
  (?x)^(
      asyncio_for_ynab/.+|
      docs/.+|
      test/.+
  )$

repos:
- repo: https://github.com/mxr/mirrors-openapi-generator-cli
  rev: 71bdf4d980586838391217b0c2c184aa132c1216  # frozen: v7.22.0
  hooks:
  - id: openapi-generator-cli
    alias: openapi-validate
    name: validate OpenAPI spec
    args: [validate, -i, config/spec.yaml]
    pass_filenames: false
    files: |
      (?x)^(
          config/.*\.ya?ml
      )$

  - id: openapi-generator-cli
    alias: openapi-generate
    name: generate async YNAB SDK
    args: [generate, -i, config/spec.yaml, -g, python, -c, config/openapi.yaml, -t, templates/python, -o, ., --minimal-update]
    pass_filenames: false
    files: |
      (?x)^(
          config/.*\.ya?ml|
          templates/python/.*\.mustache
      )$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: config/spec.yaml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --trailing-commas]
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: config/spec.yaml
- repo: https://github.com/asottile/reorder-python-imports
  rev: 7885866bd38c852b5e042c4aeef0285d715ffeee  # frozen: v3.16.0
  hooks:
  - id: reorder-python-imports
    args: [--py310-plus, --add-import, from __future__ import annotations]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 0671d8ab202c4ac093b78433ae5baf74f3fc7246  # frozen: v0.15.15
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
  hooks:
  - id: mypy
    language_version: python3.10
    additional_dependencies:
    - aioresponses
    - coverage
    - httpx>=0.28.1
    - pydantic>=2.11
    - pytest
    - pytest-asyncio
    - python-dateutil>=2.8.2
    - setuptools
    - typing-extensions>=4.7.1
- repo: https://github.com/mxr/mirrors-ty
  rev: b0cc809b854427130bbdc84b922e0e38c6c6b8eb  # frozen: v0.0.48
  hooks:
  - id: ty
    additional_dependencies:
    - aioresponses
    - coverage
    - httpx>=0.28.1
    - pydantic>=2.11
    - pytest
    - pytest-asyncio
    - python-dateutil>=2.8.2
    - setuptools
    - typing-extensions>=4.7.1
    language_version: python3.10
- repo: https://github.com/mxr/sync-typing-deps
  rev: 34b664ec01850e0d9cb4fe97c1a03d8ed71f393c  # frozen: v0.5.0
  hooks:
  - id: sync-typing-deps
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: 9257c6050c0261b8c57e712f632dc4a8010109a9  # frozen: v1.25.2
  hooks:
  - id: zizmor
    args: [--no-progress, --fix]
