packageName: asyncio_for_ynab
packageVersion: 1.86.0
packageDescription: Unofficial asyncio client for YNAB API (api.ynab.com). Not affiliated with YNAB in any way.
licenseInfo:
  name: MIT
library: httpx
